name: Python CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]   # ⬅️ change to match your local dev version

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If you have a requirements file, use it:
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Or install directly (kept for safety if requirements.txt not present)
          pip install pytest flake8

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings (disable this in CI strict mode)
          flake8 . --count --max-complexity=10 --max-line-length=100 --statistics

      - name: Run tests
        run: |
          pytest -q
